version: '2.1'
services:
  app:
    build:
      context: .
    ports:
      - "${DOCKER_APP_PORT}:80"
    volumes:
      - .:/var/www/html
    networks:
      - training
  mysql:
    image: mysql:5.7
    ports:
      - "${DOCKER_MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - training_mysql:/var/lib/mysql
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql/logs:/var/log/mysql
      - ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - training
networks:
  training:
    driver: "bridge"
volumes:
  training_mysql:
    driver: "local"
